[package]
name = "flappy_maxwell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 0

[dependencies]
rand = "0.8.5"

[dependencies.amethyst]
amethyst = "0.15.3"
features = ["vulkan"]
